finances/urls.py
from django.urls import path

from .views import user, tunnel, home, stock

app_name = "finances"
urlpatterns = [
    path("", home.index_page, name="index"),

    path("users/", user.UsersPage.as_view(), name="users"),
    path("users/<str:pk>/", user.UserPage.as_view(), name="user"),
    path("user_form/", user.user_form_page, name="user_form"),
    path("add_user/", user.add_user, name="add_user"),

    path("stocks/<str:stock_symbol>/", stock.stock_page, name="stock"),
    path("stocks/", stock.stocks_page, name="stocks"),
    path("get_symbol_suggestions/", stock.get_symbol_suggestions, name="get_symbol_suggestions"),

    path("stocks/<str:stock_symbol>/tunnel_form/", tunnel.tunnel_form_page, name="tunnel_form"),
    path("add_tunnel/", tunnel.add_tunnel, name="add_tunnel"),
    path("delete_tunnel/", tunnel.delete_tunnel, name="delete_tunnel"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('finances/', include("finances.urls")),
]

finances/models.py
from django.db import models
from django.core.validators import MinLengthValidator, EmailValidator

class User(models.Model):
    email = models.CharField(max_length=200, unique=True, validators=[EmailValidator()])
    name = models.CharField(max_length=200, validators=[MinLengthValidator(2)])

    def __str__(self):
        return self.email
    
class Tunnel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    stock_symbol = models.CharField(max_length=20)
    min_limit = models.DecimalField(max_digits=10, decimal_places=2)
    max_limit = models.DecimalField(max_digits=10, decimal_places=2)
    time_interval = models.IntegerField()

    def __str__(self):
        return (f'{self.user} watching {self.stock_symbol} ' 
                f'[{self.min_limit},{self.max_limit}] ' 
                f'{self.time_interval}min')
    
class Notification(models.Model):
    BUY = "B"
    SELL = "S"
    OPTIONS = [
        (BUY, "Comprar"),
        (SELL, "Vender"),
    ]

    tunnel = models.ForeignKey(Tunnel, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    datetime = models.DateTimeField()
    suggestion = models.CharField(max_length=1, choices=OPTIONS)
    
    def __str__(self):
        return (f'{self.tunnel.stock_symbol}' 
                f' {self.price}$ {self.datetime} ')

finances/views/home.py
from django.shortcuts import render

def index_page(request):
    return render(request, "finances/index.html")

finances/views/stock.py
import json
import requests

from django.http import JsonResponse
from django.shortcuts import render

from ..models import Tunnel
from ..utils import get_stock_data, format_stock_symbol, format_currency
from ..exceptions import EmptyStockHistory

def stocks_page(request):
    return render(request, "finances/stocks.html")

def stock_page(request, stock_symbol):
    try:
        stock_data = get_stock_data(stock_symbol)
    except EmptyStockHistory:
        context = {
            'error_message': f'A ação {stock_symbol} não possui histórico de preço.'
        }
        return render(request, 'finances/error_page.html', context)
    
    tunnels = Tunnel.objects.filter(stock_symbol=stock_symbol)
    graph_data = stock_data['graph_data']

    context = {
        'graph_data': json.dumps(graph_data),
        'stock_symbol': stock_symbol.upper(),
        'tunnels': tunnels,
        'last_price': format_currency(graph_data['y'][-1]),
        'last_price_time': graph_data['x'][-1],
        'date': stock_data['date'],
    }

    return render(request, 'finances/stock.html', context)

def get_symbol_suggestions(request):
    query = request.GET.get('query', '')
    url = 'https://symbol-search.tradingview.com/symbol_search/v3/'
    params = {
        'sort_by_country': 'BR',
        'domain': 'bovespa',
        'start': 0,
        'search_type': 'undefined',
        'lang': 'pt',
        'hl': 1,
        'text': query
    }

    response = requests.get(url, params=params)
    response_data = response.json()

    symbols = [format_stock_symbol(item['symbol']) for item in response_data.get('symbols', [])]

    return JsonResponse({'symbols': json.dumps(symbols)})

finances/views/tunnel.py
import json

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from ..models import User, Tunnel
from ..utils import get_stock_data


def tunnel_form_page(request, stock_symbol):
    stock_data = get_stock_data(stock_symbol)
    emails = list(map(lambda p: p.email, User.objects.all()))    

    context = {
        'emails': emails,
        'graph_data': json.dumps(stock_data['graph_data']),
        'date': stock_data['date'],
        'stock_symbol': stock_symbol.upper(),
    }

    return render(request, 'finances/tunnel_form.html', context)

def delete_tunnel(request):
    tunnel_id = request.POST['tunnel_id']
    tunnel = Tunnel.objects.get(pk=tunnel_id)
    tunnel.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def add_tunnel(request):
    email = request.POST['email']
    user = User.objects.get(email=email)
    stock_symbol = request.POST['stock_symbol']
    min_limit = request.POST['min_limit']
    max_limit = request.POST['max_limit']
    time_interval = request.POST['time_interval']
    tunnel = Tunnel(
        user=user, 
        stock_symbol=stock_symbol.upper(), 
        min_limit=min_limit, 
        max_limit=max_limit,
        time_interval=time_interval,
    )
    tunnel.save()
    return HttpResponseRedirect(reverse("finances:stock", args=(stock_symbol,)))

finances/views/user.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views import generic

from ..models import User, Notification


class UsersPage(generic.ListView):
    model = User
    template_name = "finances/users.html"
    context_object_name = "users"

class UserPage(generic.DetailView):
    model = User
    template_name = "finances/user.html"
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tunnels = self.get_object().tunnel_set.all()
        context["tunnels"] = tunnels

        context["notifications"] = Notification.objects.filter(tunnel__user=self.get_object())
        return context
    
def user_form_page(request):
    return render(request, "finances/user_form.html")

def add_user(request):
    name = request.POST["name"]
    email = request.POST["email"]
    user = User(name=name, email=email)
    user.save()
    return HttpResponseRedirect(reverse("finances:users"))

finances/templates/finances/error_page.html
<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <title>Algo deu errado</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
        <style>
            .body-content {
                max-width: 900px;
                margin: auto;
            }
        </style>
    </head>
    <body>
        {% include "finances/header.html" %}
        <div class="body-content">
            <h3 class="mt-4">Ops! Algo deu errado.</h3>
            {% if error_message %}
                <h5>{{ error_message }}</h5>
            {% endif %}
        </div>
    </body>
</html>

finances/templates/finances/header.html
<nav class="navbar navbar-dark bg-dark d-flex justify-content-center">
    <a class="mx-5 navbar-brand" href="{% url "finances:index" %}">Home</a>
    <a class="mx-5 navbar-brand" href="{% url "finances:stocks" %}">Ações</a>
    <a class="mx-5 navbar-brand" href="{% url "finances:users" %}">Usuários</a>
</nav>

finances/templates/finances/new_user_form.html
<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <title>Criar usuário</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
        <style>
            .body-content {
                max-width: 900px;
                margin: auto;
            }
        </style>
    </head>
    <body>
        {% include "finances/header.html" %}
        <div class="body-content">
            <form class="mt-3 row g-3" action="{% url "finances:add_user" %}" method="post">
                {% csrf_token %}
                
                <div class="col-md-6">
                    <label class="form-label" for="name">Digite seu nome:</label>
                    <input class="form-control" type="text" name="name" id="name">
                </div>
                
                <div class="col-md-6">
                    <label class="form-label" for="email">Digite seu email:</label>
                    <input class="form-control" type="email" name="email" id="email">
                </div>
                
                <div class="col-12 d-grid">
                    <input class="btn btn-primary" type="submit" value="Confirmar">
                </div>
            </form>
            
        </div>
    </body>
</html>

finances/templates/finances/notifications_table.html
<table class="table">
    <thead>
        <tr>
            <th>ID do túnel</th>
            <th>Símbolo</th>
            <th>Usuário</th>
            <th>Valor</th>
            <th>Data e Hora</th>
            <th>Sugestão</th>
        </tr>
    </thead>
    <tbody>
        {% for notification in notifications %}
            <tr>
                <td>#{{ notification.tunnel.id }}</td>
                <td>
                    <a href="{% url "finances:stock" notification.tunnel.stock_symbol %}">
                        {{ notification.tunnel.stock_symbol }}
                    </a>
                </td>
                <td>
                    <a href="{% url "finances:user" notification.tunnel.user.id %}">
                        {{ notification.tunnel.user.name }}
                    </a>
                </td>
                <td>{{ notification.price }}</td>
                <td>{{ notification.datetime }}</td>
                <td>{{ notification.get_suggestion_display }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

finances/templates/finances/stock.html
<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <title>Ação</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
        <style>
            .body-content {
                max-width: 900px;
                margin: auto;
            }
        </style>
    </head>
    <body>
        {% include "finances/header.html" %}
        <div class="body-content">
            <h3 class="mt-3"> {{ stock_symbol }} </h3>
            <h6> Último valor: {{ last_price }} às {{ last_price_time }}<br>Dia de referência: {{ date }} </h6>

            {% include "finances/stock_graph.html" %}
            
            <div class="d-grid mt-4 mb-4">
                <a class="btn btn-primary" role="button" href="{% url "finances:tunnel_form" stock_symbol %}">
                    Configurar tunel
                </a>
            </div>
            
            {% include "finances/tunnels_table.html" %}
            
        </div>
    </body>
</html>

finances/templates/finances/stock_graph.html
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-annotation"></script>

<div id="chart-wrapper">
    <canvas id="stock-chart"></canvas>
</div>

<script>
    var graph_data = JSON.parse('{{ graph_data|escapejs }}');

    var ctx = document.getElementById('stock-chart').getContext('2d');

    var stockChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: graph_data.x,
            datasets: [{
                label: 'Stock Value',
                data: graph_data.y,
                borderWidth: 2,
                borderColor: 'rgba(0, 100, 200)',
                pointStyle: 'circle',
                pointRadius: 1,
            }]
        },
        options: {
            responsive: true,
            scales: {
                x: {
                    scaleLabel: {
                        display: true,
                        labelString: 'Hour:Minute of the Day'
                    }
                },
                y: {
                    scaleLabel: {
                        display: true,
                        labelString: 'Stock Value'
                    }
                }
            }
        },
    });
</script>

<style>
    #chart-wrapper {
      width: 800px;
      margin: auto;
    }
</style>

finances/templates/finances/stocks.html
<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <title>Ações</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
        <style>
            .body-content {
                max-width: 900px;
                margin: auto;
            }
        </style>
    </head>
    <body>
        {% include "finances/header.html" %}
        <div class="body-content">
            <input class=" mt-3 form-control" type="text" id="search_input" placeholder="Pesquise por um símbolo...">
            
            <div id="loading_indicator">
                <div class="d-flex justify-content-center mt-5">
                    <div class="spinner-border" role="status">
                    </div>
                </div>
            </div>            
            <div id="empty_indicator">
                <div class="d-flex justify-content-center mt-5">
                    <h6 id="empty_indicator">Nenhum resultado encontrado</h6>
                </div>
            </div>
            <div class="mt-3 list-group" id="stock_list">
            </div>
        
        </div>
        <script>
            $(document).ready(function() {
                let $textInput = $('#search_input')
                let $suggestionList = $('#stock_list')
                let $loadingIndicator = $('#loading_indicator')
                let $emptyIndicator = $('#empty_indicator')

                function debounce(callback, timeout = 300) {
                    let timer
                    return (...args) => {
                        clearTimeout(timer)
                        timer = setTimeout(() => { callback.apply(this, args); }, timeout);
                    }
                }

                function loadSuggestions() {
                    $suggestionList.hide()
                    $emptyIndicator.hide()
                    $loadingIndicator.show()
                    var query = $textInput.val()
                    console.log('query:', query)

                    $.ajax({
                        url: '/finances/get_symbol_suggestions/',
                        method: 'GET',
                        data: { query: query },
                        dataType: 'json',
                        success: function(data) {
                            console.log('sucesso!')
                            updateSuggestionList(data)
                        },
                        error: function() {
                            console.log('Error fetching B3 api')
                        }
                    })
                }

                const onTextChanged = debounce(loadSuggestions)

                loadSuggestions()

                function updateSuggestionList(data) {
                    $suggestionList.empty();
                    let stocks = JSON.parse(data["symbols"])
                    $.each(stocks, function(index, stockSymbol) {
                        let link = $("<a>")
                            .addClass('list-group-item list-group-item-action')
                            .attr('href', '/finances/stocks/'+stockSymbol)
                            .text(stockSymbol)
                        $suggestionList.append(link)
                    })
                    if (stocks.length) {
                        console.log('tem itens')
                        $suggestionList.show()
                        $emptyIndicator.hide()
                    } else {
                        console.log('está vazia')
                        $suggestionList.hide()
                        $emptyIndicator.show()
                    }
                    $loadingIndicator.hide()
                }

                $textInput.keyup(onTextChanged)
            })
        </script>
    </body>
</html>

finances/templates/finances/symbol.html
<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <title>Ação</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
        <style>
            .body-content {
                max-width: 900px;
                margin: auto;
            }
        </style>
    </head>
    <body>
        {% include "finances/header.html" %}
        <div class="body-content">
            <h3 class="mt-3"> {{ stock_symbol }} </h3>
            <h6> Último valor: {{ last_price }} às {{ last_price_time }}<br>Dia de referência: {{ date }} </h6>

            {% include "finances/stock_graph.html" %}
            
            <div class="d-grid mt-4 mb-4">
                <a class="btn btn-primary" role="button" href="{% url "finances:tunnel_form" stock_symbol %}">
                    Configurar tunel
                </a>
            </div>
            
            {% include "finances/tunnels_table.html" %}
            
        </div>
    </body>
</html>

finances/templates/finances/tunnel_form.html
<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <title>Novo túnel</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
        <style>
            .body-content {
                max-width: 900px;
                margin: auto;
            }
        </style>
    </head>
    <body>
        {% include "finances/header.html" %}
        <div class="body-content">
            {% include "finances/stock_graph.html" %}
            
            <form class="row g-3" action="{% url "finances:add_tunnel" %}" method="post">
                {% csrf_token %}
                <input type="hidden" id="stock_symbol" name="stock_symbol" value="{{ stock_symbol }}">
                
                <div class="col-md-4">
                    <label class="form-label" for="min_limit">Limite mínimo:</label>
                    <input class="form-control" onkeyup="limitChanged()" type="number" step="0.01" name="min_limit" id="min_limit">
                </div>
                
                <div class="col-md-4">
                    <label class="form-label" for="max_limit">Limite máximo:</label>
                    <input class="form-control" onkeyup="limitChanged()" type="number" step="0.01" name="max_limit" id="max_limit">
                </div>
                
                <div class="col-md-4">
                    <label class="form-label" for="time_interval">Intervalo (em minutos):</label>
                    <input class="form-control" type="number" name="time_interval" id="time_interval">
                </div>
                
                <div class="col-12">
                    <label class="form-label" for="email">Email:</label>
                    <select class="form-select" name="email" id="email">
                        {% for email in emails %}
                        <option value="{{ email }}">{{ email }}</option>
                        {% endfor %}
                    </select>
                </div>
                
                <div class="col-12">
                    <input type="submit" class="btn btn-primary" value="Salvar">
                </div>
                
            </form>
            
            <script>
                const chart = Chart.getChart("stock-chart")
                
                function limitChanged() {
                    const limits = []
                    const min_limit = document.getElementById('min_limit').value
                    const max_limit = document.getElementById('max_limit').value
                    if (min_limit) {
                        limits.push(createLine(min_limit))
                    }
                    if (max_limit) {
                        limits.push(createLine(max_limit))
                    }
                    chart.options.plugins.annotation.annotations = limits
                    chart.update()
                }
                
                function createLine(y) {
                    return ({
                        type: 'line',
                        yMin: y,
                        yMax: y,
                        borderColor: 'rgb(255, 99, 132)',
                        borderWidth: 2,
                    })  
                }
                
            </script>
        </div>
    </body>
</html>

finances/templates/finances/tunnels_table.html
<table class="table">
    <thead>
        <tr>
            <th>ID do túnel</th>
            <th>Símbolo</th>
            <th>Usuário</th>
            <th>Limite mínimo</th>
            <th>Limite máximo</th>
            <th>Intervalo (min)</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        {% for tunnel in tunnels %}
            <tr>
                <td>#{{ tunnel.id }}</td>
                <td>
                    <a href="{% url "finances:stock" tunnel.stock_symbol %}">
                        {{ tunnel.stock_symbol }}
                    </a>
                </td>
                <td>
                    <a href="{% url "finances:user" tunnel.user.id %}">
                        {{ tunnel.user.name }}
                    </a>
                </td>
                <td>{{ tunnel.min_limit }}</td>
                <td>{{ tunnel.max_limit }}</td>
                <td>{{ tunnel.time_interval }}</td>
                <td>
                    <form action="{% url "finances:delete_tunnel" %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="tunnel_id" id="tunnel_id" value="{{ tunnel.id }}">
                        <input type="submit" class="btn btn-danger" value="Deletar">
                    </form>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

finances/templates/finances/user.html
<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <title>{{ user.name }}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
        <style>
            .body-content {
                max-width: 900px;
                margin: auto;
            }
        </style>
    </head>
    <body>
        {% include "finances/header.html" %}
        <div class="body-content">
            <h3 class="mt-3"> Pagina do usuario: {{ user.name }} </h3>
            
            <h5 class="mt-3"> Túneis cadastrados </h5>
            {% include "finances/tunnels_table.html" %}
            
            <h5 class="mt-3"> Notificações recebidas </h5>
            {% include "finances/notifications_table.html" %}
        </div>
    </body>
</html>

finances/templates/finances/user_form.html
<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <title>Criar usuário</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
        <style>
            .body-content {
                max-width: 900px;
                margin: auto;
            }
        </style>
    </head>
    <body>
        {% include "finances/header.html" %}
        <div class="body-content">
            <form class="mt-3 row g-3" action="{% url "finances:add_user" %}" method="post">
                {% csrf_token %}
                
                <div class="col-md-6">
                    <label class="form-label" for="name">Digite seu nome:</label>
                    <input class="form-control" type="text" name="name" id="name">
                </div>
                
                <div class="col-md-6">
                    <label class="form-label" for="email">Digite seu email:</label>
                    <input class="form-control" type="email" name="email" id="email">
                </div>
                
                <div class="col-12 d-grid">
                    <input class="btn btn-primary" type="submit" value="Confirmar">
                </div>
            </form>
            
        </div>
    </body>
</html>

finances/templates/finances/users.html
<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <title>Usuários</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
        <style>
            .body-content {
                max-width: 900px;
                margin: auto;
            }
        </style>
    </head>
    <body>
        {% include "finances/header.html" %}
        <div class="body-content">
            <div class="list-group mt-3" id="symbol_list">
                {% for user in users %}
                <a  class="list-group-item list-group-item-action" 
                href="{% url 'finances:user' user.id %}">
                {{ user.name }}
            </a>
            {% endfor %}
        </div>
        <div class="d-grid mt-4">
            <a class="btn btn-primary" href="{% url 'finances:user_form' %}">
                Criar novo usuario
            </a>
        </div>
        
    </div>
    </body>
</html>